language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - travis_retry composer self-update

install:
  - |
    travis_retry composer require \
      illuminate/database:$LARAVEL_VERSION \
      illuminate/container:$LARAVEL_VERSION \
      illuminate/contracts:$LARAVEL_VERSION \
      illuminate/support:$LARAVEL_VERSION \
      --no-interaction --prefer-dist --no-suggest --profile

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env: LARAVEL_VERSION=5.7
    - php: 7.1
      env: LARAVEL_VERSION=5.8
    - php: 7.2
      env: LARAVEL_VERSION=5.7
    - php: 7.2
      env: LARAVEL_VERSION=5.8
    - php: 7.2
      env: LARAVEL_VERSION=6.0
    - php: 7.2
      env: LARAVEL_VERSION=7.0
    - php: 7.3
      env: LARAVEL_VERSION=5.7
    - php: 7.3
      env: LARAVEL_VERSION=5.8
    - php: 7.3
      env: LARAVEL_VERSION=6.0
    - php: 7.3
      env: LARAVEL_VERSION=7.0

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src --report=summary -n
